### ISSUE TITLE
use interested sequence as input

### ISSUE THREAD

**Issue by xiaonalu** [crisprVerse/Tutorials#1]
Hi, I was wondering if I could use my interested sequence as input for the sgRNA design (cas9), on/off target score? If possible, is any length limitation for my input? Thanks

**Comment by Jfortin1** [comment]
Hi @xiaonalu, yes you can, see https://github.com/crisprVerse/Tutorials/tree/master/Design_Custom_Sequence. The input sequence should be longer than the length of the Cas9 spacer sequence (20nt); some on-target algorithms require some sequence context around the spacer sequence, so it might return `NA` values if the input sequence is too short.

**Comment by xiaonalu** [comment]
Awesome!!! Thanks
