### ISSUE TITLE
On Target Score Characterization in Validating Existing sgRNA Library Tutorial

### ISSUE THREAD

**Issue by stefanusbernard** [crisprVerse/Tutorials#4]
Hi, in the validating existing sgRNA library tutorial, it was mentioned that after creating the guideset, we can characterize off-target sgRNA by simply using `addOffTargetScores()` command and it directly output both CFD and MIT scores. Furthermore, I noticed we can do the same for on-target scoring by using `addOnTargetScores()` and it will output on-target score of our choice. 

However, the on-target scoring method like rule set 1 and rule set 3 will also require the 4 bp of `flank5` and 3 bp of `flank3` sequences which actually discarded from the very beginning (as we only take the 20-mer spacer sequence) and there is no such columns in the guideset that define the `flank5` and `flank3` sequences. 

I would like to know whether using `addOnTargetScores()` to validate the sgRNA library is still reliable in this case or do I need to do it manually by first defining the `flank5` and `flank3` sequences?.

**Comment by xguo-nveloptx** [comment]
I had issues using addOnTargetScroes() when following the tutorial for CRISPRko using cas12a. The error message looks like the following when using "deepcpf1"
```
Caused by error in `.validateOnTargetScoreMethods()`:
! No scoring method found for crisprNuclease 
```

**Comment by xguo-nveloptx** [comment]
I think the issue I ran into with addOnTargetScores()  is that python 2.7 is no longer supported and can't be found in current conda chanels. Any hope to move away from to python 2.7?

**Comment by Jfortin1** [comment]
Hi @stefanusbernard,

You're correct that flanking nucleotides are needed to compute most of the scores.
Based on the genomic coordinates stored in the `GuideSet` object, the `addOnTargetScores()` will automatically extract the extra needed nucleotides from the reference genome for each on-target scoring method separately, so no need to do anything from your side.
